common:
  #it can be either dev or prod
  run_mode: 'prod'

  #Of relative path format
  file_upload_base_dir: 'catssificator-upload'

  ui_server_port: '80'

db:

  #This is the sql database location
  location: 'data/database.db'
  
db-ai:

  #This is A.I. sql database location (This databaes is optional to exist in the system and it requires manually building this)
  location: 'data/database-ai.db'

cache:

  #The cache expiration setting in seconds 
  submissions_today: '60'

  submissions_in_the_past_n_days: '7200'