./query.sh "Iphone on sales" "Mobile Phones"
./query.sh "Andoid on sales" "Mobile Phones"
./query.sh "iphone overheat problems" "Mobile Phones"
./query.sh "which phone is better" "Mobile Phones"
./query.sh "David Beckham" "Soccer"
./query.sh "manchester united" "Soccer"
./query.sh "Van Gaal" "Soccer"
./query.sh "Van Diesel's wife" "Film & Television"
./query.sh "Where to drink today" "Beverages"