./query.sh "Iphone on sales" "Mobile_Devices"
./query.sh "Andoid on sales" "Mobile_Devices"
./query.sh "iphone overheat problems" "Technology"
./query.sh "which phone is better" "Mobile_Devices"
./query.sh "David Beckham" "Sports"
./query.sh "manchester united" "Sports"
./query.sh "Van Gaal" "Sports"
./query.sh "Van Diesel's wife" "Television"
./query.sh "Where to drink today" "Berverages"